CREATE TABLE {{QA_SCHEMA}}.{{SCRATCH_TABLE}} (id integer PRIMARY KEY, status text);
INSERT INTO {{QA_SCHEMA}}.{{SCRATCH_TABLE}} (id, status) VALUES (1, 'CREATED');
SELECT id, status FROM {{QA_SCHEMA}}.{{SCRATCH_TABLE}} ORDER BY id;
UPDATE {{QA_SCHEMA}}.{{SCRATCH_TABLE}} SET status = 'UPDATED' WHERE id = 1;
SELECT id, status FROM {{QA_SCHEMA}}.{{SCRATCH_TABLE}} ORDER BY id;
DELETE FROM {{QA_SCHEMA}}.{{SCRATCH_TABLE}} WHERE id = 1;
SELECT COUNT(*) AS remaining_rows FROM {{QA_SCHEMA}}.{{SCRATCH_TABLE}};
DROP TABLE {{QA_SCHEMA}}.{{SCRATCH_TABLE}};
