<#
Runs the complete local quality gate: compilation, database MCP tests, E2E
helper tests, and an offline smoke test. Any failed stage stops the script and
returns a failing process exit code.
#>

#region Script execution settings
$ErrorActionPreference = "Stop"
#endregion Script execution settings

#region Workspace path resolution and prerequisite check
# Derive the shared virtual environment and fail early when setup was skipped.
$ProjectRoot = Split-Path -Parent $PSScriptRoot
$WorkspaceRoot = Split-Path -Parent $ProjectRoot
$Python = Join-Path $WorkspaceRoot ".venv\Scripts\python.exe"

if (-not (Test-Path $Python)) {
    throw "Virtual environment missing. Run MCP\scripts\setup.ps1 first."
}
#endregion Workspace path resolution and prerequisite check

#region Isolated verification workspace
$SystemTemp = [System.IO.Path]::GetFullPath([System.IO.Path]::GetTempPath())
$TestTemp = Join-Path $SystemTemp ("mcp-verify-{0}-{1}" -f $PID, [guid]::NewGuid().ToString("N"))
New-Item -ItemType Directory -Path $TestTemp -Force | Out-Null
#endregion Isolated verification workspace

#region Complete verification pipeline
try {
    # Keep generated bytecode and pytest temporary files outside the
    # OneDrive-managed working tree, where editor locks can otherwise interfere.
    $env:PYTHONPYCACHEPREFIX = Join-Path $TestTemp "pycache"
    $PythonFiles = @(& git -C $WorkspaceRoot ls-files "*.py")
    if ($LASTEXITCODE -ne 0 -or $PythonFiles.Count -eq 0) {
        throw "Could not enumerate tracked Python files for compilation."
    }
    $AbsolutePythonFiles = @($PythonFiles | ForEach-Object { Join-Path $WorkspaceRoot $_ })

    #region Tracked Python compilation
    & $Python -m py_compile @AbsolutePythonFiles
    if ($LASTEXITCODE -ne 0) { throw "Compilation failed." }
    #endregion Tracked Python compilation

    #region MCP SDK compatibility verification
    # Check the exact API used by server.py before running tests that may not
    # import the server entry point directly.
    $FastMCPCompatibilityCheck = @'
import importlib.metadata as metadata
from mcp.server.fastmcp import FastMCP

print('MCP version:', metadata.version('mcp'))
print('FastMCP import OK')
'@
    & $Python -c $FastMCPCompatibilityCheck
    if ($LASTEXITCODE -ne 0) {
        throw "FastMCP compatibility verification failed. Run MCP\scripts\setup.ps1."
    }
    #endregion MCP SDK compatibility verification

    #region Database MCP tests and offline smoke test
    Push-Location $ProjectRoot
    try {
        & $Python -m pytest -q --basetemp (Join-Path $TestTemp "database-tests")
        if ($LASTEXITCODE -ne 0) { throw "Database MCP test suite failed." }

        # The deterministic demo connector verifies startup without live credentials.
        $env:DB_TYPE = "demo"
        $env:DB_HOST = "demo-local"
        $env:DB_DATABASE = "qa_demo"
        $env:DB_USERNAME = ""
        $env:DB_PASSWORD = ""
        $env:DB_CONNECTION_OPTIONS = "{}"
        $env:DB_ACTIVE_PROFILE = "demo-local"
        & $Python tests\smoke_test.py
        if ($LASTEXITCODE -ne 0) { throw "Smoke test failed." }
    } finally {
        Pop-Location
    }
    #endregion Database MCP tests and offline smoke test

    #region External E2E helper tests
    Push-Location $WorkspaceRoot
    try {
        & $Python -m pytest -q .\tests -p no:cacheprovider --basetemp (Join-Path $TestTemp "e2e-tests")
        if ($LASTEXITCODE -ne 0) { throw "E2E helper test suite failed." }
    } finally {
        Pop-Location
    }
    #endregion External E2E helper tests

    Write-Host "All verification gates passed."
} finally {
    #region Temporary workspace cleanup
    $ResolvedTestTemp = [System.IO.Path]::GetFullPath($TestTemp)
    if ((Test-Path -LiteralPath $ResolvedTestTemp) -and $ResolvedTestTemp.StartsWith($SystemTemp, [System.StringComparison]::OrdinalIgnoreCase)) {
        Remove-Item -LiteralPath $ResolvedTestTemp -Recurse -Force -ErrorAction SilentlyContinue
    }
    #endregion Temporary workspace cleanup
}
#endregion Complete verification pipeline
