SELECT CURRENT_DATABASE() AS DATABASE_NAME,
       COUNT_IF(TABLE_SCHEMA = UPPER('{{RAW_SCHEMA}}') AND TABLE_NAME = UPPER('{{SOURCE_FLIGHTS_TABLE}}')) AS SOURCE_FLIGHTS_EXISTS,
       COUNT_IF(TABLE_SCHEMA = UPPER('{{ANALYTICS_SCHEMA}}') AND TABLE_NAME = UPPER('{{TARGET_TABLE}}')) AS TARGET_EXISTS
FROM {{SNOWFLAKE_DATABASE}}.INFORMATION_SCHEMA.TABLES;
