SELECT COUNT(*) AS RAW_FLIGHT_ROWS,
       COUNT_IF(NULLIF(TRIM(YEAR), '') IS NULL) AS BLANK_YEAR_ROWS,
       COUNT_IF(NULLIF(TRIM(AIRLINE), '') IS NULL) AS BLANK_AIRLINE_ROWS,
       COUNT_IF(NULLIF(TRIM(ORIGIN_AIRPORT), '') IS NULL) AS BLANK_ORIGIN_ROWS,
       COUNT_IF(NULLIF(TRIM(DESTINATION_AIRPORT), '') IS NULL) AS BLANK_DESTINATION_ROWS
FROM {{SNOWFLAKE_DATABASE}}.{{RAW_SCHEMA}}.{{SOURCE_FLIGHTS_TABLE}};
