SELECT COUNT(*) AS ANALYTICS_ROWS,
       COUNT_IF(IS_CANCELLED) AS CANCELLED_ROWS,
       COUNT_IF(IS_DIVERTED) AS DIVERTED_ROWS,
       COUNT_IF(IS_ON_TIME) AS ON_TIME_ROWS,
       COUNT_IF(DATA_QUALITY_ISSUE) AS DATA_QUALITY_ISSUE_ROWS,
       COUNT_IF(AIRLINE_NAME IS NULL) AS MISSING_AIRLINE_LOOKUP_ROWS,
       COUNT_IF(ORIGIN_AIRPORT_NAME IS NULL) AS MISSING_ORIGIN_LOOKUP_ROWS,
       COUNT_IF(DESTINATION_AIRPORT_NAME IS NULL) AS MISSING_DESTINATION_LOOKUP_ROWS
FROM {{SNOWFLAKE_DATABASE}}.{{ANALYTICS_SCHEMA}}.{{TARGET_TABLE}};
