SELECT r.RAW_ROWS, t.ANALYTICS_ROWS,
       t.ANALYTICS_ROWS - r.RAW_ROWS AS ROW_DIFFERENCE
FROM (SELECT COUNT(*) AS RAW_ROWS FROM {{SNOWFLAKE_DATABASE}}.{{RAW_SCHEMA}}.{{SOURCE_FLIGHTS_TABLE}}) r
CROSS JOIN (SELECT COUNT(*) AS ANALYTICS_ROWS FROM {{SNOWFLAKE_DATABASE}}.{{ANALYTICS_SCHEMA}}.{{TARGET_TABLE}}) t;
