SELECT
  COUNT_IF(FLIGHT_KEY IS NULL) AS NULL_FLIGHT_KEYS,
  COUNT(*) - COUNT(DISTINCT FLIGHT_KEY) AS DUPLICATE_FLIGHT_KEYS,
  COUNT_IF(IS_CANCELLED AND CANCELLATION_REASON IS NULL) AS CANCELLED_WITHOUT_REASON,
  COUNT_IF(ORIGIN_AIRPORT = DESTINATION_AIRPORT) AS SAME_ORIGIN_DESTINATION
FROM {{SNOWFLAKE_DATABASE}}.{{ANALYTICS_SCHEMA}}.{{TARGET_TABLE}};
