CREATE TABLE {{SNOWFLAKE_DATABASE}}.{{QA_SCHEMA}}.{{SCRATCH_TABLE}} (ID INTEGER PRIMARY KEY, STATUS VARCHAR);
INSERT INTO {{SNOWFLAKE_DATABASE}}.{{QA_SCHEMA}}.{{SCRATCH_TABLE}} (ID, STATUS) VALUES (1, 'CREATED');
SELECT ID, STATUS FROM {{SNOWFLAKE_DATABASE}}.{{QA_SCHEMA}}.{{SCRATCH_TABLE}} ORDER BY ID;
UPDATE {{SNOWFLAKE_DATABASE}}.{{QA_SCHEMA}}.{{SCRATCH_TABLE}} SET STATUS = 'UPDATED' WHERE ID = 1;
SELECT ID, STATUS FROM {{SNOWFLAKE_DATABASE}}.{{QA_SCHEMA}}.{{SCRATCH_TABLE}} ORDER BY ID;
DELETE FROM {{SNOWFLAKE_DATABASE}}.{{QA_SCHEMA}}.{{SCRATCH_TABLE}} WHERE ID = 1;
SELECT COUNT(*) AS REMAINING_ROWS FROM {{SNOWFLAKE_DATABASE}}.{{QA_SCHEMA}}.{{SCRATCH_TABLE}};
DROP TABLE {{SNOWFLAKE_DATABASE}}.{{QA_SCHEMA}}.{{SCRATCH_TABLE}};
